/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * LNK URL Shortener API
 * A URL shortener service API
 * OpenAPI spec version: 1.0
 */
import { customInstance } from './axios-instance';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface HandlersCreateURLRequest {
  url: string;
}

export interface HandlersCreateURLResponse {
  original_url?: string;
  short_url?: string;
}

export interface HandlersErrorResponse {
  error?: string;
}

export type GetHealth200 = {[key: string]: string};

export type GetShortUrl308 = {[key: string]: string};

export type GetShortUrl500 = {[key: string]: string};

/**
 * Check if the API is running
 * @summary Health check endpoint
 */
export const getHealth = <TData = AxiosResponse<GetHealth200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return customInstance<GetHealth200>({
      method: 'get',
      url: `/health`,
      ...options,
    }) as Promise<TData>;
  }

/**
 * Create a short URL from a long URL
 * @summary Create a short URL
 */
export const postShorten = <TData = AxiosResponse<HandlersCreateURLResponse>>(
    handlersCreateURLRequest: HandlersCreateURLRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return customInstance<HandlersCreateURLResponse>({
      method: 'post',
      url: `/shorten`,
      data: handlersCreateURLRequest,
      ...options,
    }) as Promise<TData>;
  }

/**
 * Get the original URL from a short URL
 * @summary Get original URL by short URL
 */
export const getShortUrl = <TData = AxiosResponse<unknown>>(
    shortUrl: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return customInstance<unknown>({
      method: 'get',
      url: `/${shortUrl}`,
      ...options,
    }) as Promise<TData>;
  }

export type GetHealthResult = AxiosResponse<GetHealth200>
export type PostShortenResult = AxiosResponse<HandlersCreateURLResponse>
export type GetShortUrlResult = AxiosResponse<unknown>
