// Code generated by mockery v2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRedis is an autogenerated mock type for the Redis type
type MockRedis struct {
	mock.Mock
}

// Incr provides a mock function with given fields: ctx, key
func (_m *MockRedis) Incr(ctx context.Context, key string) (int64, error) {
	_ret := _m.Called(ctx, key)

	if len(_ret) == 0 {
		panic("no return value specified for Incr")
	}

	var r0 int64
	var r1 error
	if rf, ok := _ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := _ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = _ret.Get(0).(int64)
	}

	if rf, ok := _ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = _ret.Error(1)
	}

	return r0, r1
}

// NewMockRedis creates a new instance of MockRedis. It also registers a testing interface on the mock and a cleanup function to assert the mock's expectations.
func NewMockRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedis {
	mock := &MockRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
